<?php

namespace Database\Seeders;

use App\Models\v1\Portal\Card;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Card::truncate();
        Card::insert([
            [
                'section_id' => 2,
                'title' => 'Online Degree Programs',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/category-1.svg'),
                'icon' => '',
                'color' => 'green',
                'badge_text' => '4 Courses',
                'sticker_text' => '',
                'component' => 'Programs',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 2,
                'title' => 'Non-Degree Programs',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/category-2.svg'),
                'icon' => '',
                'color' => 'red',
                'badge_text' => '7 Courses',
                'sticker_text' => '',
                'component' => 'Programs',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 2,
                'title' => 'Off-Campus Programs',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/category-3.svg'),
                'icon' => '',
                'color' => 'blue',
                'badge_text' => '8 Courses',
                'sticker_text' => '',
                'component' => 'Programs',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 2,
                'title' => 'Hybrid Distance Programs',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/category-4.svg'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => '8 Courses',
                'sticker_text' => '',
                'component' => 'Programs',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 4,
                'title' => 'Build Responsive Real- World Websites with HTML and CSS',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/course-1.jpg'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => 'Biginner',
                'sticker_text' => '3 Weeks',
                'component' => 'Courses',
                'rating' => 5.0,
                'price' => 29.00,
                'infos' => json_encode([
                    '8 Lessons', '3 Hours/Week',
                ]),
                'link' => null,
            ],
            [
                'section_id' => 4,
                'title' => 'Java Programming Masterclass for Software',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/course-2.jpg'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => 'Biginner',
                'sticker_text' => '8 Weeks',
                'component' => 'Courses',
                'rating' => 4.5,
                'price' => 49.00,
                'infos' => json_encode([
                    '15 Lessons', '13 Hours/Week',
                ]),
                'link' => null,
            ],
            [
                'section_id' => 4,
                'title' => 'The Complete Camtasia Course for Content Creators',
                'content' => fake()->sentence(10),
                'image' => asset('images/pe/course-3.jpg'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => 'Biginner',
                'sticker_text' => '3 Weeks',
                'component' => 'Courses',
                'rating' => 4.9,
                'price' => 35.00,
                'infos' => json_encode([
                    '13 Lessons', '8 Hours/Week',
                ]),
                'link' => null,
            ],
            [
                'section_id' => 6,
                'title' => '29.3k',
                'content' => 'STUDENT ENROLLED',
                'image' => '',
                'icon' => '',
                'color' => 'green',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Counter',
                'rating' => 4.9,
                'price' => 35.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 6,
                'title' => '32.4K',
                'content' => 'CLASS COMPLETED',
                'image' => '',
                'icon' => '',
                'color' => 'red',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Counter',
                'rating' => 4.9,
                'price' => 35.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 6,
                'title' => '32.4K',
                'content' => 'SATISFACTION RATE',
                'image' => '',
                'icon' => '',
                'color' => 'purple',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Counter',
                'rating' => 4.9,
                'price' => 35.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 6,
                'title' => '354+',
                'content' => 'TOP INSTRUCTORS',
                'image' => '',
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Counter',
                'rating' => 4.9,
                'price' => 35.00,
                'infos' => json_encode([]),
                'link' => null,
            ],
            [
                'section_id' => 10,
                'title' => 'Shaapir Prio',
                'content' => 'Assistant Director',
                'image' => asset('images/pe/instructor-1.png'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Team',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([
                    ['type' => 'facebook', 'link' => '#'],
                    ['type' => 'twitter', 'link' => '#'],
                    ['type' => 'instagram', 'link' => '#'],
                    ['type' => 'linkedin', 'link' => '#'],
                ]),
                'link' => null,
            ],
            [
                'section_id' => 10,
                'title' => 'Sellina',
                'content' => 'Director',
                'image' => asset('images/pe/instructor-2.png'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Team',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([
                    ['type' => 'facebook', 'link' => '#'],
                    ['type' => 'twitter', 'link' => '#'],
                    ['type' => 'instagram', 'link' => '#'],
                    ['type' => 'linkedin', 'link' => '#'],
                ]),
                'link' => null,
            ],
            [
                'section_id' => 10,
                'title' => 'John Smith',
                'content' => 'Data Analyst',
                'image' => asset('images/pe/instructor-3.png'),
                'icon' => '',
                'color' => 'yellow',
                'badge_text' => '',
                'sticker_text' => '',
                'component' => 'Team',
                'rating' => null,
                'price' => 0.00,
                'infos' => json_encode([
                    ['type' => 'facebook', 'link' => '#'],
                    ['type' => 'twitter', 'link' => '#'],
                    ['type' => 'instagram', 'link' => '#'],
                    ['type' => 'linkedin', 'link' => '#'],
                ]),
                'link' => null,
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
